In [2]:
from pymongo import MongoClient
import pandas as pd

In [3]:
client = MongoClient('mongodb://localhost:27017/')
db = client.instagram

In [4]:
df = pd.DataFrame(client.instagram.subscriptions.find())
df

,_id,user_id,subscriber_status,id,name,photo,full_info
0,96709902022043003929,9670990202,1,2043003929,khaalid_abdi_ali,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '2043003929', 'username': 'khaalid_abdi..."
1,77090578106033212949,7709057810,1,6033212949,mahmoud.alaa.9,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '6033212949', 'username': 'mahmoud.alaa..."
2,96709902022259847077,9670990202,1,2259847077,hse_aneek,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '2259847077', 'username': 'hse_aneek', ..."
3,770905781017888808812,7709057810,1,17888808812,kkv_236,https://scontent-iad3-1.cdninstagram.com/v/t51...,"{'id': '17888808812', 'username': 'kkv_236', '..."
4,96709902021107450891,9670990202,1,1107450891,abdelrahman_elbashdesigner,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '1107450891', 'username': 'abdelrahman_..."
...,...,...,...,...,...,...,...
460,77090578108547792177,7709057810,1,8547792177,layla_aldlfe1,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '8547792177', 'username': 'layla_aldlfe..."
461,770905781038576815175,7709057810,1,38576815175,rafal.997,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '38576815175', 'username': 'rafal.997',..."
462,77090578107506492115,7709057810,1,7506492115,_____.ary.____,https://instagram.fkwi3-1.fna.fbcdn.net/v/t51....,"{'id': '7506492115', 'username': '_____.ary.__..."
463,7709057810491775876,7709057810,1,491775876,egathecha,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '491775876', 'username': 'egathecha', '..."
464,77090578105721291090,7709057810,1,5721291090,museb57,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '5721291090', 'username': 'museb57', 'f..."

In [5]:
df[df['name'].isin(['hse_aneek', 'mom_call_me_moses'])]

,_id,user_id,subscriber_status,id,name,photo,full_info
2,96709902022259847077,9670990202,1,2259847077,hse_aneek,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '2259847077', 'username': 'hse_aneek', ..."
198,967099020247806230,9670990202,1,47806230,mom_call_me_moses,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '47806230', 'username': 'mom_call_me_mo..."

In [9]:
df[df['user_id'].isin(['7709057810'])]

,_id,user_id,subscriber_status,id,name,photo,full_info
1,77090578106033212949,7709057810,1,6033212949,mahmoud.alaa.9,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '6033212949', 'username': 'mahmoud.alaa..."
3,770905781017888808812,7709057810,1,17888808812,kkv_236,https://scontent-iad3-1.cdninstagram.com/v/t51...,"{'id': '17888808812', 'username': 'kkv_236', '..."
5,77090578102059625070,7709057810,1,2059625070,saxenaavlokita,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '2059625070', 'username': 'saxenaavloki..."
7,770905781031229497539,7709057810,1,31229497539,desire_of_coding____,https://scontent-fco1-1.cdninstagram.com/v/t51...,"{'id': '31229497539', 'username': 'desire_of_c..."
9,77090578103621159948,7709057810,1,3621159948,rawath174,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '3621159948', 'username': 'rawath174', ..."
...,...,...,...,...,...,...,...
460,77090578108547792177,7709057810,1,8547792177,layla_aldlfe1,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '8547792177', 'username': 'layla_aldlfe..."
461,770905781038576815175,7709057810,1,38576815175,rafal.997,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '38576815175', 'username': 'rafal.997',..."
462,77090578107506492115,7709057810,1,7506492115,_____.ary.____,https://instagram.fkwi3-1.fna.fbcdn.net/v/t51....,"{'id': '7506492115', 'username': '_____.ary.__..."
463,7709057810491775876,7709057810,1,491775876,egathecha,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '491775876', 'username': 'egathecha', '..."
464,77090578105721291090,7709057810,1,5721291090,museb57,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '5721291090', 'username': 'museb57', 'f..."

In [8]:
df[df['user_id'].isin(['9670990202'])]

,_id,user_id,subscriber_status,id,name,photo,full_info
0,96709902022043003929,9670990202,1,2043003929,khaalid_abdi_ali,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '2043003929', 'username': 'khaalid_abdi..."
2,96709902022259847077,9670990202,1,2259847077,hse_aneek,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '2259847077', 'username': 'hse_aneek', ..."
4,96709902021107450891,9670990202,1,1107450891,abdelrahman_elbashdesigner,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '1107450891', 'username': 'abdelrahman_..."
6,96709902026085070896,9670990202,1,6085070896,s_a_n_d_h_y_a_2490,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '6085070896', 'username': 's_a_n_d_h_y_..."
8,96709902028082395419,9670990202,1,8082395419,arani_sushmitha_,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '8082395419', 'username': 'arani_sushmi..."
...,...,...,...,...,...,...,...
416,96709902021795853325,9670990202,1,1795853325,nafisaislamfariba,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '1795853325', 'username': 'nafisaislamf..."
417,967099020234217961410,9670990202,1,34217961410,warda.fazal,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '34217961410', 'username': 'warda.fazal..."
418,96709902027079172215,9670990202,1,7079172215,0___jerry,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '7079172215', 'username': '0___jerry', ..."
419,967099020225362161071,9670990202,1,25362161071,_rahul___joshi__,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '25362161071', 'username': '_rahul___jo..."
420,96709902026100216813,9670990202,1,6100216813,prateekparauliya,https://scontent-hel2-1.cdninstagram.com/v/t51...,"{'id': '6100216813', 'username': 'prateekparau..."